name: flutter_gbaccetta_feed_app
description: GBAccetta Medium portfolio.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  http: ^1.1.0
  webfeed_plus: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true